# Generated by Django 5.0.6 on 2024-07-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.TextField(default='Obi & Sons'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_date',
            field=models.DateField(null=True),
        ),
    ]
